export type Desc = {
  songID: string
  moggSong: string
  moggMainSong: string
  title: string
  artist: string
  midiFile: string
  fusionSpatialized: string
  fusionUnspatialized: string
  targetDrums: string
  sustainSongRight: string
  moggSustainSongRight: string
  sustainSongLeft: string
  moggSustainSongLeft: string
  fxSong: string
  moggFxSong: string
  tempo: number
  songEndEvent: string
  prerollSeconds: number
  useMidiForCues: boolean
  hidden: boolean
  author: string
  offset: number
  previewStartSeconds: number
  bookmarks: []
  customExpert: string
  customAdvanced: string
  customModerate: string
  customBeginner: string
}
